blank_issues_enabled: true
contact_links:
  - name: MyMusicBot Support
    url: https://t.me/MyMusicBotSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://MyMusicBot.tech/
    about: Documentation for getting started with bot.
